### ISSUE TITLE
How to solve the problem of Loss NaN

### ISSUE THREAD

**Issue by lumosity4tpj** [bayesgroup/deepbayes-2019#7]
I wanted to implement sparse VD in convolution, but loss was NaN. Would anyone like to provide the code in the case of convolution? I am not very familiar with theano in the original code of the paper, and I still have problems after rewriting.
This is my code:
![image](https://user-images.githubusercontent.com/46916880/85944800-236a5880-b96c-11ea-921d-6daf97bbcc46.png)

**Comment by senya-ashukha** [comment]
Hey, 

Thank you for checking out at the assignment code! 

1) lrt_std should not depend on the bias 
2) make sure you are using adam or something adaptive 

You can also look at tf implementation here https://github.com/google-research/google-research/blob/master/state_of_sparsity/layers/variational_dropout/nn.py#L347.

**Comment by lumosity4tpj** [comment]
Thanks a lot!!! Because of the problem, I tried a lot. Removing bias seems to work.
